import http from "../services/httpService";

const products = http.get("http://localhost:3000/api/v1/products");

const skus = [
  {
    id: 1,
    parentId: "kirby_adventure_vv",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 2,
    parentId: "kirby_adventure_ii",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 3,
    parentId: "kirby_adventure_bb",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 4,
    parentId: "kirby_adventure_gg",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 5,
    parentId: "kirby_adventure_yy",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 6,
    parentId: "kirby_adventure_oo",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 7,
    parentId: "kirby_adventure_rr",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 8,
    parentId: "kirby_adventure_fod",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9,
    parentId: "kirby_adventure_fod",
    type: "sku",
    options: {
      size: "Small",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 10,
    parentId: "kirby_adventure_fod",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 11,
    parentId: "kirby_adventure_fod",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 12,
    parentId: "kirby_adventure_fod",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 13,
    parentId: "kirby_adventure_fod",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 14,
    parentId: "smash_ladies_villager",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 15,
    parentId: "smash_ladies_villager",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 16,
    parentId: "smash_ladies_wii_fit",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 17,
    parentId: "smash_ladies_wii_fit",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 18,
    parentId: "smash_ladies_zelda",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 19,
    parentId: "smash_ladies_zelda",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 20,
    parentId: "smash_ladies_sheik",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 21,
    parentId: "smash_ladies_sheik",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 22,
    parentId: "smash_ladies_palutena",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 23,
    parentId: "smash_ladies_palutena",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 24,
    parentId: "smash_ladies_samus",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 25,
    parentId: "smash_ladies_samus",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 26,
    parentId: "smash_ladies_jigglypuff",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 27,
    parentId: "smash_ladies_jigglypuff",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 28,
    parentId: "smash_ladies_wendy",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 29,
    parentId: "smash_ladies_wendy",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 30,
    parentId: "smash_ladies_peach",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 31,
    parentId: "smash_ladies_peach",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 32,
    parentId: "smash_ladies_rosalina",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 33,
    parentId: "smash_ladies_rosalina",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 34,
    parentId: "smash_ladies_bayonetta",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 35,
    parentId: "smash_ladies_bayonetta",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 36,
    parentId: "smash_ladies_corrin",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 37,
    parentId: "smash_ladies_corrin",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 38,
    parentId: "smash_ladies_lucina",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 39,
    parentId: "smash_ladies_lucina",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 40,
    parentId: "smash_ladies_robin",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 41,
    parentId: "smash_ladies_robin",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 42,
    parentId: "kirby_parasol",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 43,
    parentId: "kirby_parasol",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 44,
    parentId: "kirby_parasol",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 45,
    parentId: "kirby_parasol",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 46,
    parentId: "kirby_parasol",
    type: "sku",
    options: {
      size: "Smedium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 47,
    parentId: "kirby_wispy_woods",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 48,
    parentId: "kirby_wispy_woods",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 49,
    parentId: "kirby_crystal_shards",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 50,
    parentId: "kirby_crystal_shards",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 51,
    parentId: "mario_rosalina",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 52,
    parentId: "mario_geno",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 53,
    parentId: "mario_geno",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 54,
    parentId: "mario_birds",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 55,
    parentId: "mario_birds",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 56,
    parentId: "mario_birds",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 57,
    parentId: "mario_paper_battle",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 58,
    parentId: "mario_paper_battle",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 59,
    parentId: "mario_paper_battle",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 60,
    parentId: "mario_paper_luigi",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 61,
    parentId: "mario_paper_luigi",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 62,
    parentId: "mario_paper_luigi",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 63,
    parentId: "mario_paper_peach",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 64,
    parentId: "mario_paper_peach",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 65,
    parentId: "pokemon_sweets_pumpkaboo",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 66,
    parentId: "pokemon_sweets_pumpkaboo",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 67,
    parentId: "pokemon_sweets_cakepops",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 68,
    parentId: "pokemon_sweets_cakepops",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 69,
    parentId: "pokemon_sweets_slurpuff",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 70,
    parentId: "pokemon_sweets_slurpuff",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 71,
    parentId: "pokemon_sweets_vulpix",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 72,
    parentId: "pokemon_sweets_vulpix",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 73,
    parentId: "pokemon_sweets_raichu",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 74,
    parentId: "pokemon_sweets_raichu",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 75,
    parentId: "pokemon_sweets_bellossom",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 76,
    parentId: "pokemon_sweets_bellossom",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 77,
    parentId: "pokemon_sweets_bellossom",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 78,
    parentId: "pokemon_sweets_macarons",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 79,
    parentId: "pokemon_lilly",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 80,
    parentId: "pokemon_lilly",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 81,
    parentId: "pokemon_lilly",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 82,
    parentId: "pokemon_snap",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 83,
    parentId: "pokemon_snap",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 84,
    parentId: "pokemon_snap",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 85,
    parentId: "pokemon_snap",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 86,
    parentId: "pokemon_snap",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 87,
    parentId: "banjo_kazooie",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 88,
    parentId: "banjo_kazooie",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 89,
    parentId: "zelda_malon",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 90,
    parentId: "zelda_malon",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 91,
    parentId: "zelda_malon",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 92,
    parentId: "zelda_saria",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 93,
    parentId: "zelda_saria",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 94,
    parentId: "zelda_saria",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 95,
    parentId: "ice_climbers",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 9,
  },
  {
    id: 96,
    parentId: "ice_climbers",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 97,
    parentId: "ice_climbers",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 98,
    parentId: "ice_climbers",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 3,
  },
  {
    id: 99,
    parentId: "ice_climbers",
    type: "sku",
    options: {
      size: "Smedium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 100,
    parentId: "harvest_moon",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 101,
    parentId: "harvest_moon",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Thin",
    },

    inventory: 10,
  },
  {
    id: 102,
    parentId: "kingdom_hearts_beach",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 103,
    parentId: "kingdom_hearts_beach",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 104,
    parentId: "pokemon_alphabet_gen1",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 105,
    parentId: "pokemon_alphabet_gen2",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 106,
    parentId: "pokemon_alphabet_gen2",
    type: "sku",
    options: {
      size: "Large",
      finish: "Thin",
    },

    inventory: 10,
  },
  {
    id: 107,
    parentId: "deltarune_cake",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 11,
  },
  {
    id: 108,
    parentId: "deltarune_cake",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Holographic",
    },
    inventory: 2,
  },
  {
    id: 109,
    parentId: "deltarune_cake",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 8,
  },
  {
    id: 110,
    parentId: "deltarune_cake",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 2,
  },
  {
    id: 111,
    parentId: "undertale_frisk_flowey",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 112,
    parentId: "undertale_frisk_flowey",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 113,
    parentId: "undertale_frisk_flowey",
    type: "sku",
    options: {
      size: "Smedium",
      finish: "Matte",
    },
    inventory: 6,
  },
  {
    id: 114,
    parentId: "undertale_frisk_flowey",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 8,
  },
  {
    id: 115,
    parentId: "undertale_cavestory",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 1,
  },
  {
    id: 116,
    parentId: "undertale_cavestory",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 9,
  },
  {
    id: 117,
    parentId: "undertale_cavestory",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Thin",
    },
    inventory: 10,
  },
  {
    id: 118,
    parentId: "undertale_cavestory",
    type: "sku",
    options: {
      size: "Large",
      finish: "Thin",
    },
    inventory: 10,
  },
  {
    id: 119,
    parentId: "cavestory_quote",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 120,
    parentId: "gravity_falls_dipper",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 121,
    parentId: "gravity_falls_dipper",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 7,
  },
  {
    id: 122,
    parentId: "gravity_falls_dipper",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 8,
  },
  {
    id: 123,
    parentId: "gravity_falls_mabel",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 124,
    parentId: "gravity_falls_mabel",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 1,
  },
  {
    id: 125,
    parentId: "gravity_falls_mabel",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 6,
  },
  {
    id: 126,
    parentId: "gravity_falls_bill",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 15,
  },
  {
    id: 127,
    parentId: "gravity_falls_bill_v1",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 128,
    parentId: "gravity_falls_bill",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 11,
  },
  {
    id: 129,
    parentId: "gravity_falls_bill_v1",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Thin",
    },
    inventory: 51,
  },
  {
    id: 130,
    parentId: "gravity_falls_bill",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 5,
  },
  {
    id: 131,
    parentId: "gravity_falls_bill",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 3,
  },
  {
    id: 132,
    parentId: "shera_shitpost_catra",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 133,
    parentId: "shera_shitpost_adora",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 134,
    parentId: "sherlock_scarf",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 14,
  },
  {
    id: 135,
    parentId: "sherlock_scarf",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 9,
  },
  {
    id: 136,
    parentId: "sherlock_wedding",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 5,
  },
  {
    id: 137,
    parentId: "sherlock_wedding",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 7,
  },
  {
    id: 138,
    parentId: "steven_universe_catfingers",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 139,
    parentId: "madoka_magica_quote",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 17,
  },
  {
    id: 140,
    parentId: "madoka_magica_quote",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 7,
  },
  {
    id: 141,
    parentId: "madoka_magica_quote",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 9,
  },
  {
    id: 142,
    parentId: "inuyasha_sesshoumaru_group",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 143,
    parentId: "inuyasha_sesshoumaru_group",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 14,
  },
  {
    id: 144,
    parentId: "inuyasha_sesshoumaru_group",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 11,
  },
  {
    id: 145,
    parentId: "dennou_coil_circle_of_children",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 146,
    parentId: "dennou_coil_circle_of_children",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 8,
  },
  {
    id: 147,
    parentId: "dennou_coil_circle_of_children",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Holographic",
    },
    inventory: 1,
  },
  {
    id: 148,
    parentId: "dennou_coil_circle_of_children",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 149,
    parentId: "dennou_coil_circle_of_children",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 2,
  },
  {
    id: 150,
    parentId: "natsume_yuujinchou_return_name",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 151,
    parentId: "natsume_yuujinchou_return_name",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 152,
    parentId: "natsume_yuujinchou_return_name",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 153,
    parentId: "ghibli_arrietty",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 154,
    parentId: "ghibli_arrietty",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 155,
    parentId: "ghibli_arrietty",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 2,
  },
  {
    id: 156,
    parentId: "ghibli_cat_returns",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 157,
    parentId: "nichijou_skyfall",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 5,
  },
  {
    id: 158,
    parentId: "nichijou_skyfall",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 159,
    parentId: "nichijou_skyfall",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 3,
  },
  {
    id: 160,
    parentId: "magical_girls_amu",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 161,
    parentId: "magical_girls_sakura",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 162,
    parentId: "magical_girls_ahiru",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 163,
    parentId: "magical_girls_rue",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 164,
    parentId: "magical_girls_maya",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 165,
    parentId: "magical_girls_akko",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 166,
    parentId: "magical_girls_kagome",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 167,
    parentId: "magical_girls_full_moon",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 168,
    parentId: "cardcaptor_sakura_cashcaptors",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 1,
  },
  {
    id: 169,
    parentId: "cardcaptor_sakura_cashcaptors",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 5,
  },
  {
    id: 170,
    parentId: "cardcaptor_sakura_cashcaptors",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 171,
    parentId: "hunter_x_pokemon_gon",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 172,
    parentId: "hunter_x_pokemon_gon",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 173,
    parentId: "hunter_x_pokemon_killua",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 174,
    parentId: "hunter_x_pokemon_killua",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 175,
    parentId: "hunter_x_pokemon_alluka",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 176,
    parentId: "hunter_x_pokemon_alluka",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 177,
    parentId: "hunter_x_pokemon_leorio",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 178,
    parentId: "hunter_x_pokemon_leorio",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 179,
    parentId: "hunter_x_pokemon_kurapika",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 180,
    parentId: "hunter_x_pokemon_kurapika",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 181,
    parentId: "cats_and_tea_rain",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 182,
    parentId: "cats_and_tea_rain",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 7,
  },
  {
    id: 183,
    parentId: "cats_and_tea_rain",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Thin",
    },
    inventory: 51,
  },
  {
    id: 184,
    parentId: "cats_and_tea_rain",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 185,
    parentId: "cats_and_tea_rain",
    type: "sku",
    options: {
      size: "Large",
      finish: "Thin",
    },
    inventory: 48,
  },
  {
    id: 186,
    parentId: "cats_and_tea_fire",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 6,
  },
  {
    id: 187,
    parentId: "cats_and_tea_fire_v1",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 8,
  },
  {
    id: 188,
    parentId: "cats_and_tea_fire",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 11,
  },
  {
    id: 189,
    parentId: "cats_and_tea_fire_v1",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 190,
    parentId: "cats_and_tea_fire",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 191,
    parentId: "cats_and_tea_fire_v1",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 6,
  },
  {
    id: 192,
    parentId: "cats_and_tea_cafe",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 193,
    parentId: "cats_and_tea_cafe",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 194,
    parentId: "cats_and_tea_cafe",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 195,
    parentId: "cats_and_tea_sadness",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 196,
    parentId: "cats_and_tea_sadness",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 1,
  },
  {
    id: 197,
    parentId: "bees_beelines",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 198,
    parentId: "bees_dance",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 199,
    parentId: "bees_felt",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 200,
    parentId: "bees_fruit",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 1,
  },
  {
    id: 201,
    parentId: "bees_ribbon",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 202,
    parentId: "tea_makes_me_happy",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 203,
    parentId: "tea_makes_me_happy",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 204,
    parentId: "all_you_need_is_cake",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 1,
  },
  {
    id: 205,
    parentId: "all_you_need_is_cake",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 3,
  },
  {
    id: 206,
    parentId: "mushishi_light_river",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 207,
    parentId: "mushishi_light_river",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 2,
  },
  {
    id: 208,
    parentId: "princess_tutu_healing_touch",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 16,
  },
  {
    id: 209,
    parentId: "princess_tutu_healing_touch",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 6,
  },
  {
    id: 210,
    parentId: "princess_tutu_healing_touch",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 4,
  },
  {
    id: 211,
    parentId: "heck_bird",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 15,
  },
  {
    id: 212,
    parentId: "loaf_cat",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 7,
  },
  {
    id: 213,
    parentId: "loaf_cat",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Holographic",
    },
    inventory: 1,
  },
  {
    id: 214,
    parentId: "harvest_moon_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 15,
  },
  {
    id: 215,
    parentId: "harvest_moon_bookmark",
    type: "sku",
    options: {
      side: "Front",
    },
    inventory: 1,
  },
  {
    id: 216,
    parentId: "harvest_moon_bookmark",
    type: "sku",
    options: {
      side: "Back",
    },
    inventory: 5,
  },
  {
    id: 217,
    parentId: "bomberman_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 14,
  },
  {
    id: 218,
    parentId: "yoshi_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 7,
  },
  {
    id: 219,
    parentId: "yoshi_bookmark",
    type: "sku",
    options: {
      side: "Front",
    },
    inventory: 1,
  },
  {
    id: 220,
    parentId: "kirby_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 32,
  },
  {
    id: 221,
    parentId: "monkey_island_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 4,
  },
  {
    id: 222,
    parentId: "cat_cafe_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 34,
  },
  {
    id: 223,
    parentId: "cat_cafe_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Misprint",
    },
    inventory: 21,
  },
  {
    id: 224,
    parentId: "pokemon_birds_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 12,
  },
  {
    id: 225,
    parentId: "zelda_emojis_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 226,
    parentId: "zelda_phrases_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 7,
  },
  {
    id: 227,
    parentId: "bees_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 23,
  },
  {
    id: 228,
    parentId: "bees_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Misprint",
    },
    inventory: 16,
  },
  {
    id: 229,
    parentId: "kirby_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 16,
  },
  {
    id: 230,
    parentId: "kirby_stickers",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Misprint",
    },
    inventory: 8,
  },
  {
    id: 231,
    parentId: "zelda_rupees_stickers",
    type: "sku",
    options: {
      size: "Small",
      quality: "Good",
    },
    inventory: 35,
  },
  {
    id: 232,
    parentId: "zelda_fairies_stickers",
    type: "sku",
    options: {
      size: "Large",
      quality: "Good",
    },
    inventory: 8,
  },
  {
    id: 233,
    parentId: "zelda_spirit_stones_stickers",
    type: "sku",
    options: {
      size: "Large",
      quality: "Good",
    },
    inventory: 0,
  },
  {
    id: 234,
    parentId: "zelda_items_stickers",
    type: "sku",
    options: {
      size: "Large",
      quality: "Good",
    },
    inventory: 8,
  },
  {
    id: 235,
    parentId: "bees_accessories_stickers",
    type: "sku",
    options: {
      size: "Large",
      quality: "Good",
    },
    inventory: 9,
  },
  {
    id: 236,
    parentId: "bees_stickers_v1",
    type: "sku",
    options: {
      size: "Large",
      quality: "Good",
    },
    inventory: 8,
  },
  {
    id: 237,
    parentId: "single_sticker",
    type: "sku",
    options: {
      size: "Tiny",
    },
    inventory: 13,
  },
  {
    id: 238,
    parentId: "single_sticker",
    type: "sku",
    options: {
      size: "Small",
    },
    inventory: 58,
  },
  {
    id: 239,
    parentId: "single_sticker",
    type: "sku",
    options: {
      size: "Large",
    },
    inventory: 10,
  },
  {
    id: 240,
    parentId: "bee_lines_zine",
    type: "sku",
    inventory: 46,
    price: 10,
  },
  {
    id: 241,
    parentId: "sweets_zine",
    type: "sku",
    inventory: 26,
    price: 8,
  },
  {
    id: 242,
    parentId: "tayce_t_zine",
    type: "sku",
    inventory: 13,
    price: 5,
  },
  {
    id: 243,
    parentId: "bee_stationery",
    type: "sku",
    options: {
      size: "6 sheets",
      color: "Pink",
    },

    inventory: 4,
  },
  {
    id: 244,
    parentId: "bee_stationery",
    type: "sku",
    options: {
      size: "6 sheets",
      color: "Blue",
    },
    inventory: 2,
  },
  {
    id: 245,
    parentId: "bee_stationery",
    type: "sku",
    options: {
      size: "6 sheets",
      color: "Yellow",
    },
    inventory: 3,
  },
  {
    id: 246,
    parentId: "bee_stationery",
    type: "sku",
    options: {
      size: "6 sheets",
      color: "Combo",
    },
    inventory: 7,
  },
  {
    id: 247,
    parentId: "bee_stationery",
    type: "sku",
    options: {
      size: "12 sheets",
      color: "Combo",
    },
    inventory: 2,
  },
  {
    id: 248,
    parentId: "undertale_button_frisk",
    type: "sku",
    inventory: 10,
  },
  {
    id: 249,
    parentId: "undertale_button_chara",
    type: "sku",
    inventory: 10,
  },
  {
    id: 250,
    parentId: "undertale_button_flowey",
    type: "sku",
    inventory: 10,
  },
  {
    id: 251,
    parentId: "undertale_button_asriel",
    type: "sku",
    inventory: 10,
  },
  {
    id: 252,
    parentId: "undertale_button_toriel",
    type: "sku",
    inventory: 10,
  },
  {
    id: 253,
    parentId: "undertale_button_asgore",
    type: "sku",
    inventory: 10,
  },
  {
    id: 254,
    parentId: "undertale_button_papyrus",
    type: "sku",
    inventory: 10,
  },
  {
    id: 255,
    parentId: "undertale_button_sans",
    type: "sku",
    inventory: 10,
  },
  {
    id: 256,
    parentId: "undertale_button_undyne",
    type: "sku",
    inventory: 10,
  },
  {
    id: 257,
    parentId: "undertale_button_alphys",
    type: "sku",
    inventory: 10,
  },
  {
    id: 258,
    parentId: "undertale_button_mettaton_humanoid",
    type: "sku",
    inventory: 10,
  },
  {
    id: 259,
    parentId: "undertale_button_mettaton_box",
    type: "sku",
    inventory: 10,
  },
  {
    id: 260,
    parentId: "undertale_button_muffet",
    type: "sku",
    inventory: 10,
  },
  {
    id: 261,
    parentId: "undertale_button_bratty",
    type: "sku",
    inventory: 10,
  },
  {
    id: 262,
    parentId: "undertale_button_catty",
    type: "sku",
    inventory: 10,
  },
  {
    id: 263,
    parentId: "undertale_button_nice_cream",
    type: "sku",
    inventory: 10,
  },
  {
    id: 264,
    parentId: "undertale_button_burgerpants",
    type: "sku",
    inventory: 10,
  },
  {
    id: 265,
    parentId: "undertale_button_temmie",
    type: "sku",
    inventory: 10,
  },
  {
    id: 266,
    parentId: "undertale_button_grillby",
    type: "sku",
    inventory: 10,
  },
  {
    id: 267,
    parentId: "undertale_button_monster_kid",
    type: "sku",
    inventory: 10,
  },
  {
    id: 268,
    parentId: "undertale_button_napstablook",
    type: "sku",
    inventory: 10,
  },
  {
    id: 269,
    parentId: "undertale_button_lesser_dog_head",
    type: "sku",
    inventory: 10,
  },
  {
    id: 270,
    parentId: "undertale_button_lesser_dog_straight_neck",
    type: "sku",
    inventory: 10,
  },
  {
    id: 271,
    parentId: "undertale_button_lesser_dog_bent_neck",
    type: "sku",
    inventory: 10,
  },
  {
    id: 272,
    parentId: "undertale_button_lesser_dog_body",
    type: "sku",
    inventory: 10,
  },
  {
    id: 273,
    parentId: "paper_mario_button_goombario",
    type: "sku",
    inventory: 10,
  },
  {
    id: 274,
    parentId: "paper_mario_button_kooper",
    type: "sku",
    inventory: 10,
  },
  {
    id: 275,
    parentId: "paper_mario_button_bombette",
    type: "sku",
    inventory: 10,
  },
  {
    id: 276,
    parentId: "paper_mario_button_parakarry",
    type: "sku",
    inventory: 10,
  },
  {
    id: 277,
    parentId: "paper_mario_button_bow",
    type: "sku",
    inventory: 10,
  },
  {
    id: 278,
    parentId: "paper_mario_button_watt",
    type: "sku",
    inventory: 10,
  },
  {
    id: 279,
    parentId: "paper_mario_button_sushie",
    type: "sku",
    inventory: 10,
  },
  {
    id: 280,
    parentId: "paper_mario_button_lakilester",
    type: "sku",
    inventory: 10,
  },
  {
    id: 281,
    parentId: "paper_mario_button_peach",
    type: "sku",
    inventory: 10,
  },
  {
    id: 282,
    parentId: "paper_mario_button_luigi",
    type: "sku",
    inventory: 10,
  },
  {
    id: 283,
    parentId: "paper_mario_button_mario",
    type: "sku",
    inventory: 10,
  },
  {
    id: 284,
    parentId: "mario_button_goomba",
    type: "sku",
    inventory: 10,
  },
  {
    id: 285,
    parentId: "mario_button_koopa",
    type: "sku",
    inventory: 10,
  },
  {
    id: 286,
    parentId: "mario_button_boo",
    type: "sku",
    inventory: 10,
  },
  {
    id: 287,
    parentId: "mario_button_lakitu",
    type: "sku",
    inventory: 10,
  },
  {
    id: 288,
    parentId: "mario_button_piranha",
    type: "sku",
    inventory: 10,
  },
  {
    id: 289,
    parentId: "mario_button_shyguy",
    type: "sku",
    inventory: 10,
  },
  {
    id: 290,
    parentId: "mario_button_buzzy",
    type: "sku",
    inventory: 10,
  },
  {
    id: 291,
    parentId: "mario_button_blooper",
    type: "sku",
    inventory: 10,
  },
  {
    id: 292,
    parentId: "mario_button_chomp",
    type: "sku",
    inventory: 10,
  },
  {
    id: 293,
    parentId: "mario_button_bobomb",
    type: "sku",
    inventory: 10,
  },
  {
    id: 294,
    parentId: "kirby_button_kirby",
    type: "sku",
    inventory: 10,
  },
  {
    id: 295,
    parentId: "kirby_button_waddle_dee",
    type: "sku",
    inventory: 10,
  },
  {
    id: 296,
    parentId: "kirby_button_dedede",
    type: "sku",
    inventory: 10,
  },
  {
    id: 297,
    parentId: "kirby_button_metaknight",
    type: "sku",
    inventory: 10,
  },
  {
    id: 298,
    parentId: "kirby_button_magolor",
    type: "sku",
    inventory: 10,
  },
  {
    id: 299,
    parentId: "kirby_button_waddle_doo",
    type: "sku",
    inventory: 10,
  },
  {
    id: 300,
    parentId: "kirby_button_bronto",
    type: "sku",
    inventory: 10,
  },
  {
    id: 301,
    parentId: "kirby_button_scarfy_cute",
    type: "sku",
    inventory: 10,
  },
  {
    id: 302,
    parentId: "kirby_button_scarfy_terrifying",
    type: "sku",
    inventory: 10,
  },
  {
    id: 303,
    parentId: "kirby_button_sparky",
    type: "sku",
    inventory: 10,
  },
  {
    id: 304,
    parentId: "kirby_button_chilly",
    type: "sku",
    inventory: 10,
  },
  {
    id: 305,
    parentId: "kirby_button_poppy",
    type: "sku",
    inventory: 10,
  },
  {
    id: 306,
    parentId: "touhou_button_suika",
    type: "sku",
    inventory: 10,
  },
  {
    id: 307,
    parentId: "touhou_button_reimu",
    type: "sku",
    inventory: 10,
  },
  {
    id: 308,
    parentId: "touhou_button_koishi",
    type: "sku",
    inventory: 10,
  },
  {
    id: 309,
    parentId: "touhou_button_youmu",
    type: "sku",
    inventory: 10,
  },
  {
    id: 310,
    parentId: "touhou_button_sakuya",
    type: "sku",
    inventory: 10,
  },
  {
    id: 311,
    parentId: "touhou_button_marisa",
    type: "sku",
    inventory: 10,
  },
  {
    id: 312,
    parentId: "otgw_button_wirt",
    type: "sku",
    inventory: 10,
  },
  {
    id: 313,
    parentId: "otgw_button_greg",
    type: "sku",
    inventory: 10,
  },
  {
    id: 314,
    parentId: "otgw_button_beatrice",
    type: "sku",
    inventory: 10,
  },
  {
    id: 315,
    parentId: "otgw_button_frog",
    type: "sku",
    inventory: 10,
  },
  {
    id: 316,
    parentId: "otgw_button_beast",
    type: "sku",
    inventory: 10,
  },
  {
    id: 317,
    parentId: "sonic_silver_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 318,
    parentId: "cavestory_quote_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 319,
    parentId: "bastion_kid_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 320,
    parentId: "pokemon_zubat_azumarill_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 321,
    parentId: "sailor_moon_luna_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 322,
    parentId: "cardcaptor_sakura_kero_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 323,
    parentId: "cat_yarn_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 324,
    parentId: "cat_loaf_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 325,
    parentId: "succulent_cactus_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 326,
    parentId: "succulent_aloe_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 327,
    parentId: "bird_branch_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 328,
    parentId: "penguin_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 329,
    parentId: "pokemon_go_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 330,
    parentId: "pokemon_vulpix_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 331,
    parentId: "kirby_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 332,
    parentId: "commission",
    type: "sku",
    inventory: 10,
  },
  {
    id: 333,
    parentId: "pokemon_alphabet_gen1_a",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 334,
    parentId: "pokemon_alphabet_gen1_a",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 335,
    parentId: "pokemon_alphabet_gen1_b",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 336,
    parentId: "pokemon_alphabet_gen1_b",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 337,
    parentId: "pokemon_alphabet_gen1_c",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 338,
    parentId: "pokemon_alphabet_gen1_c",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 339,
    parentId: "pokemon_alphabet_gen1_d",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 340,
    parentId: "pokemon_alphabet_gen1_d",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 341,
    parentId: "pokemon_alphabet_gen1_e",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 342,
    parentId: "pokemon_alphabet_gen1_e",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 343,
    parentId: "pokemon_alphabet_gen1_f",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 344,
    parentId: "pokemon_alphabet_gen1_f",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 345,
    parentId: "pokemon_alphabet_gen1_g",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 346,
    parentId: "pokemon_alphabet_gen1_g",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 347,
    parentId: "pokemon_alphabet_gen1_h",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 348,
    parentId: "pokemon_alphabet_gen1_h",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 349,
    parentId: "pokemon_alphabet_gen1_i",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 350,
    parentId: "pokemon_alphabet_gen1_i",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 351,
    parentId: "pokemon_alphabet_gen1_j",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 352,
    parentId: "pokemon_alphabet_gen1_j",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 353,
    parentId: "pokemon_alphabet_gen1_k",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 354,
    parentId: "pokemon_alphabet_gen1_k",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 355,
    parentId: "pokemon_alphabet_gen1_l",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 356,
    parentId: "pokemon_alphabet_gen1_l",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 357,
    parentId: "pokemon_alphabet_gen1_m",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 358,
    parentId: "pokemon_alphabet_gen1_m",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 359,
    parentId: "pokemon_alphabet_gen1_n",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 360,
    parentId: "pokemon_alphabet_gen1_n",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 361,
    parentId: "pokemon_alphabet_gen1_o",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 362,
    parentId: "pokemon_alphabet_gen1_o",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 363,
    parentId: "pokemon_alphabet_gen1_p",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 364,
    parentId: "pokemon_alphabet_gen1_p",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 365,
    parentId: "pokemon_alphabet_gen1_q",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 366,
    parentId: "pokemon_alphabet_gen1_q",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 367,
    parentId: "pokemon_alphabet_gen1_r",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 368,
    parentId: "pokemon_alphabet_gen1_r",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 369,
    parentId: "pokemon_alphabet_gen1_s",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 370,
    parentId: "pokemon_alphabet_gen1_s",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 371,
    parentId: "pokemon_alphabet_gen1_t",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 372,
    parentId: "pokemon_alphabet_gen1_t",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 373,
    parentId: "pokemon_alphabet_gen1_u",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 374,
    parentId: "pokemon_alphabet_gen1_u",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 375,
    parentId: "pokemon_alphabet_gen1_v",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 376,
    parentId: "pokemon_alphabet_gen1_v",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 377,
    parentId: "pokemon_alphabet_gen1_w",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 378,
    parentId: "pokemon_alphabet_gen1_w",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 379,
    parentId: "pokemon_alphabet_gen1_x",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 380,
    parentId: "pokemon_alphabet_gen1_x",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 381,
    parentId: "pokemon_alphabet_gen1_y",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 382,
    parentId: "pokemon_alphabet_gen1_y",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 383,
    parentId: "pokemon_alphabet_gen1_z",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 384,
    parentId: "pokemon_alphabet_gen1_z",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 385,
    parentId: "pokemon_alphabet_gen2_a",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 386,
    parentId: "pokemon_alphabet_gen2_a",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 387,
    parentId: "pokemon_alphabet_gen2_b",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 388,
    parentId: "pokemon_alphabet_gen2_b",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 389,
    parentId: "pokemon_alphabet_gen2_c",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 390,
    parentId: "pokemon_alphabet_gen2_c",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 391,
    parentId: "pokemon_alphabet_gen2_d",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 392,
    parentId: "pokemon_alphabet_gen2_d",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 393,
    parentId: "pokemon_alphabet_gen2_e",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 394,
    parentId: "pokemon_alphabet_gen2_e",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 395,
    parentId: "pokemon_alphabet_gen2_f",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 396,
    parentId: "pokemon_alphabet_gen2_f",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 397,
    parentId: "pokemon_alphabet_gen2_g",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 398,
    parentId: "pokemon_alphabet_gen2_g",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 399,
    parentId: "pokemon_alphabet_gen2_h",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 400,
    parentId: "pokemon_alphabet_gen2_h",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 401,
    parentId: "pokemon_alphabet_gen2_i",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 402,
    parentId: "pokemon_alphabet_gen2_i",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 403,
    parentId: "pokemon_alphabet_gen2_j",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 404,
    parentId: "pokemon_alphabet_gen2_j",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 405,
    parentId: "pokemon_alphabet_gen2_k",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 406,
    parentId: "pokemon_alphabet_gen2_k",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 407,
    parentId: "pokemon_alphabet_gen2_l",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 408,
    parentId: "pokemon_alphabet_gen2_l",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 409,
    parentId: "pokemon_alphabet_gen2_m",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 410,
    parentId: "pokemon_alphabet_gen2_m",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 411,
    parentId: "pokemon_alphabet_gen2_n",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 412,
    parentId: "pokemon_alphabet_gen2_n",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 413,
    parentId: "pokemon_alphabet_gen2_o",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 414,
    parentId: "pokemon_alphabet_gen2_o",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 415,
    parentId: "pokemon_alphabet_gen2_p",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 416,
    parentId: "pokemon_alphabet_gen2_p",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 417,
    parentId: "pokemon_alphabet_gen2_q",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 418,
    parentId: "pokemon_alphabet_gen2_q",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 419,
    parentId: "pokemon_alphabet_gen2_r",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 420,
    parentId: "pokemon_alphabet_gen2_r",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 421,
    parentId: "pokemon_alphabet_gen2_s",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 422,
    parentId: "pokemon_alphabet_gen2_s",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 423,
    parentId: "pokemon_alphabet_gen2_t",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 424,
    parentId: "pokemon_alphabet_gen2_t",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 425,
    parentId: "pokemon_alphabet_gen2_u",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 426,
    parentId: "pokemon_alphabet_gen2_u",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 427,
    parentId: "pokemon_alphabet_gen2_u_v1",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 428,
    parentId: "pokemon_alphabet_gen2_u_v1",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 429,
    parentId: "pokemon_alphabet_gen2_v",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 430,
    parentId: "pokemon_alphabet_gen2_v",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 431,
    parentId: "pokemon_alphabet_gen2_w",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 432,
    parentId: "pokemon_alphabet_gen2_w",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 433,
    parentId: "pokemon_alphabet_gen2_x",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 434,
    parentId: "pokemon_alphabet_gen2_x",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 435,
    parentId: "pokemon_alphabet_gen2_y",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 436,
    parentId: "pokemon_alphabet_gen2_y",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 437,
    parentId: "pokemon_alphabet_gen2_z",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 438,
    parentId: "pokemon_alphabet_gen2_z",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 439,
    parentId: "holographic_sparkly_button",
    type: "sku",
    inventory: 100,
    price: 1,
  },
];

const sets = [
  {
    id: "kirby_postcards",
    title: "Kirby's Adventure Postcard Set",
    type: "set",
    skuIds: [1, 2, 3, 4, 5, 6, 7, 8],
    price: 30,
    discount: 10,
  },
  {
    id: "kirby_postcards_holo",
    title: "Kirby's Adventure Postcard Set - Holographic",
    type: "set",
    skuIds: [1, 2, 3, 4, 5, 6, 7, 9],
    price: 30,
    discount: 11,
  },
  {
    id: "pokebet_gen1_mini",
    title: "Pokemon Alphabet Mini (Gen 1)",
    type: "set",
    skuIds: [
      333,
      335,
      337,
      339,
      341,
      343,
      345,
      347,
      349,
      351,
      353,
      355,
      357,
      359,
      361,
      363,
      365,
      367,
      369,
      371,
      373,
      375,
      377,
      379,
      381,
      383,
    ],
    price: 35,
    discount: 17,
  },
  {
    id: "pokebet_gen1_small",
    title: "Pokemon Alphabet Small (Gen 1)",
    type: "set",
    skuIds: [
      334,
      336,
      338,
      340,
      342,
      344,
      346,
      348,
      350,
      352,
      354,
      356,
      358,
      360,
      362,
      364,
      366,
      368,
      370,
      372,
      374,
      376,
      378,
      380,
      382,
      384,
    ],
    price: 65,
    discount: 65,
  },
  {
    id: "pokebet_gen2_mini",
    title: "Pokemon Alphabet Mini (Gen 2)",
    type: "set",
    skuIds: [
      385,
      387,
      389,
      391,
      393,
      395,
      397,
      399,
      401,
      403,
      405,
      407,
      409,
      411,
      413,
      415,
      417,
      419,
      421,
      423,
      425,
      429,
      431,
      433,
      435,
      437,
    ],
    price: 35,
    discount: 17,
  },
  {
    id: "pokebet_gen2_small",
    title: "Pokemon Alphabet Small (Gen 2)",
    type: "set",
    skuIds: [
      386,
      388,
      390,
      392,
      394,
      396,
      398,
      400,
      402,
      404,
      406,
      408,
      410,
      412,
      414,
      416,
      418,
      420,
      422,
      424,
      426,
      430,
      432,
      434,
      436,
      438,
    ],
    price: 65,
    discount: 65,
  },
  {
    id: "pokebet_mini",
    title: "Pokemon Alphabet Mini (All Letters)",
    type: "set",
    skuIds: [
      333,
      335,
      337,
      339,
      341,
      343,
      345,
      347,
      349,
      351,
      353,
      355,
      357,
      359,
      361,
      363,
      365,
      367,
      369,
      371,
      373,
      375,
      377,
      379,
      381,
      383,
      385,
      387,
      389,
      391,
      393,
      395,
      397,
      399,
      401,
      403,
      405,
      407,
      409,
      411,
      413,
      415,
      417,
      419,
      421,
      423,
      425,
      427,
      429,
      431,
      433,
      435,
      437,
    ],
  },
  {
    id: "pokebet_small",
    title: "Pokemon Alphabet Small (All Letters)",
    type: "set",
    skuIds: [
      334,
      336,
      338,
      340,
      342,
      344,
      346,
      348,
      350,
      352,
      354,
      356,
      358,
      360,
      362,
      364,
      366,
      368,
      370,
      372,
      374,
      376,
      378,
      380,
      382,
      384,
      386,
      388,
      390,
      392,
      394,
      396,
      398,
      400,
      402,
      404,
      406,
      408,
      410,
      412,
      414,
      416,
      418,
      420,
      422,
      424,
      426,
      428,
      430,
      432,
      434,
      436,
      438,
    ],
  },
  {
    id: "undertale_buttons",
    title: "Undertale Buttons",
    type: "set",
    skuIds: [
      248,
      249,
      250,
      251,
      252,
      253,
      254,
      255,
      256,
      257,
      258,
      259,
      260,
      261,
      262,
      263,
      264,
      265,
      266,
      267,
      268,
      269,
      270,
      271,
      272,
    ],
    price: 25,
    discount: 25,
  },
  {
    id: "paper_mario_buttons",
    title: "Paper Mario Buttons",
    type: "set",
    skuIds: [273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283],
    price: 15,
    discount: 7,
  },
  {
    id: "mario_buttons",
    title: "Mario Baddies Buttons",
    type: "set",
    skuIds: [284, 285, 286, 287, 288, 289, 290, 291, 292, 293],
    price: 10,
    discount: 10,
  },
  {
    id: "kirby_buttons",
    title: "Kirby Buttons",
    type: "set",
    skuIds: [294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305],
    price: 15,
    discount: 9,
  },
  {
    id: "otgw_buttons",
    title: "Over the Garden Wall Buttons",
    type: "set",
    skuIds: [312, 313, 314, 315, 316],
    price: 7,
    discount: 3,
  },
];

const discountRules = [
  {
    id: 1,
    title: "3 Mini Prints for $5",
    medium: "print",
    quantity: 3,
    size: "Mini",
    discount: 1,
  },
  {
    id: 2,
    title: "3 Small Prints for $12",
    medium: "print",
    quantity: 3,
    size: "Small",
    discount: 3,
  },
  {
    id: 3,
    title: "4 Medium Prints for $30",
    medium: "print",
    quantity: 4,
    size: "Medium",
    discount: 10,
  },
  {
    id: 4,
    title: "2 Large Prints for $25",
    medium: "print",
    quantity: 2,
    size: "Large",
    discount: 5,
  },
  {
    id: 5,
    title: "3 Buttons for $5",
    medium: "button",
    quantity: 3,
    discount: 1,
  },
  {
    id: 6,
    title: "3 Sticker Sheets for $10",
    medium: "stickers",
    quantity: 3,
    size: "Sheet",
    discount: 5,
  },
];

export function getProducts() {
  return products;
}

export function getProduct(id) {
  return products.find(p => p.id === id);
}

export function getSkus() {
  return skus;
}

export function getSku(id) {
  return skus.find(s => s.id === id);
}

export function getSets() {
  return sets;
}

export function getSet(id) {
  return sets.find(s => s.id === id);
}

export function getDiscountRules() {
  return discountRules;
}
