const products = [
  //   {
  //     id: "kirby_adventure_vv",
  //     type: "design",
  //     artist: "Jupebox",
  //     medium: "print",
  //     title: "Vegetable Valley",
  //     imageUrl: "",
  //     productOptions: {
  //       size: ["Small"],
  //       finish: ["Matte"]
  //     },
  //     skuIds: [1]
  //   }
  {
    id: "guide_to_marths",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "A Guide To Marths",
    imageUrl: "",
    productOptions: {
      size: ["Large"],
      finish: ["Matte"],
    },
    skuIds: [9001],
  },
  {
    id: "wonder_woman",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Wonder Woman",
    imageUrl: "",
    productOptions: {
      size: ["Medium", "Large"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9002, 9003, 9004],
  },
  {
    id: "rick_and_morty",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Rick & Morty",
    imageUrl: "",
    productOptions: {
      size: ["Medium", "Large"],
      finish: ["Matte"],
    },
    skuIds: [9005, 9006],
  },
  {
    id: "love_live_ice_cream",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Love Live Ice Cream",
    imageUrl: "",
    productOptions: {
      size: ["Medium", "Large"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9007, 9008, 9009],
  },
  {
    id: "illumi_natu",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Illuminatu",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9010, 9011, 9012, 9013],
  },
  {
    id: "hisoka",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Hisoka with Pokemon",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte"],
    },
    skuIds: [9014, 9015, 9016],
  },
  {
    id: "together_breakfast",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Together Breakfast",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte", "Holographic", "Thin"],
    },
    skuIds: [9017, 9018, 9019, 9020, 9021],
  },
  //todo
  {
    id: "live_laugh_love_chara_undertale",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Live Laugh Love",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9022, 9023, 9024, 9025],
  },
  {
    id: "junkrat_bakugou_my_hero_academia_overwatch",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Exploding Trash Boys",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium"],
      finish: ["Matte"],
    },
    skuIds: [9026, 9027],
  },
  {
    id: "samus_zero_suit",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Zero Suit Samus",
    imageUrl: "",
    productOptions: {
      size: ["Mini", "Small", "Medium"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9028, 9029, 9030],
  },
  {
    id: "narumitsu_ace_attorney_edgeworth_phoenix",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Chained by Fate",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte", "Thin"],
    },
    skuIds: [9031, 9032, 9033, 9034, 9035],
  },
  {
    id: "wind_waker_house_soup",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Grandma's Soup",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium"],
      finish: ["Matte"],
    },
    skuIds: [9036, 9037],
  },
  {
    id: "bubble_bobble",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Bubble Bobble",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium"],
      finish: ["Matte"],
    },
    skuIds: [9038, 9039],
  },
  {
    id: "sakura_regret_space",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Sakura in Space",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte"],
    },
    skuIds: [9040, 9041, 9042],
  },
  {
    id: "sherlock_redbeard_kids",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Kidlock",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium", "Large"],
      finish: ["Matte"],
    },
    skuIds: [9043, 9044, 9045],
  },
  {
    id: "sherlock_wedding_planning",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Sherlock Wedding Planning",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium"],
      finish: ["Matte"],
    },
    skuIds: [9046, 9047],
  },
  {
    id: "high_tea_overwatch_mccree_hanzo_nani_the_fuck",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "It's Hiiiiigh Tea",
    imageUrl: "",
    productOptions: {
      size: ["Small"],
      finish: ["Matte"],
    },
    skuIds: [9048],
  },
  {
    id: "moira_guess_youll_die_overwatch",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Moira Shitpost",
    imageUrl: "",
    productOptions: {
      size: ["Mini"],
      finish: ["Matte"],
    },
    skuIds: [9049],
  },
  {
    id: "pikachus_apples_trees",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Pikachu Forest",
    imageUrl: "",
    productOptions: {
      size: ["Mini", "Small"],
      finish: ["Matte"],
    },
    skuIds: [9050, 9051],
  },
  {
    id: "morth_portrait",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Morth",
    imageUrl: "",
    productOptions: {
      size: ["Mini"],
      finish: ["Matte"],
    },
    skuIds: [9052],
  },
  {
    id: "corgi_beer_watson",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Corgi Nap Time",
    imageUrl: "",
    productOptions: {
      size: ["Small"],
      finish: ["Matte"],
    },
    skuIds: [9053],
  },
  {
    id: "mob_psycho_salt",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Mob Psycho - Sparkly Salt",
    imageUrl: "",
    productOptions: {
      size: ["Large"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9054, 9055],
  },
  {
    id: "my_hero_academia_arcade",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Hero Catch!",
    imageUrl: "",
    productOptions: {
      size: ["Large"],
      finish: ["Matte", "Holographic"],
    },
    skuIds: [9056, 9057],
  },
  {
    id: "shera_dnd",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "DM Must Be Strong",
    imageUrl: "",
    productOptions: {
      size: ["Medium", "Large"],
      finish: ["Matte"],
    },
    skuIds: [9058, 9059],
  },
  {
    id: "full_moon_wo_sagashite",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "I found it",
    imageUrl: "",
    productOptions: {
      size: ["Small", "Medium"],
      finish: ["Matte"],
    },
    skuIds: [9060, 9061],
  },
  {
    id: "sonic_shitpost_gun",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Say it.",
    imageUrl: "",
    productOptions: {
      size: ["Mini"],
      finish: ["Matte"],
    },
    skuIds: [9062],
  },
  {
    id: "sonic_shitpost_nya",
    type: "design",
    artist: "Yuli",
    medium: "print",
    title: "Uhh... nya~?",
    imageUrl: "",
    productOptions: {
      size: ["Mini"],
      finish: ["Matte"],
    },
    skuIds: [9063],
  },
  // {
  //   id: "little_witch_academia_flying",
  //   type: "design",
  //   artist: "Yuli",
  //   medium: "print",
  //   title: "I Believe I Can Fly",
  //   imageUrl: "",
  //   productOptions: {
  //       size: ["Large"],
  //       finish: ["Matte", "Holographic"]
  //   },
  //   skuIds: [91]
  // },
  //   {
  //     id: "sonic_postcard_sonic",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Sonic",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_shadow",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Shadow",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_silver",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Silver",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_blaze",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Blaze",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_tails",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Tails",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_knuckles",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Knuckles",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_amy",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Amy",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_cream",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Cream",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  //   {
  //     id: "sonic_postcard_rouge",
  //     type: "design",
  //     artist: "Yuli",
  //     medium: "print",
  //     title: "Chao Garden - Rouge",
  //     imageUrl: "",
  //     productOptions: {
  //         size: ["Small"],
  //         finish: ["Matte"]
  //     },
  //     skuIds: [91]
  //   },
  {
    id: "narumitsu_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "Phoenix & Edgeworth",
    imageUrl: "",
    skuIds: [9064],
  },
  {
    id: "maya_pearl_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "Maya & Pearl",
    imageUrl: "",
    skuIds: [9065],
  },
  {
    id: "moira_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "Scientist Moira",
    imageUrl: "",
    skuIds: [9066],
  },
  {
    id: "mei_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "Melon Mei",
    imageUrl: "",
    skuIds: [9067],
  },
  {
    id: "dva_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "Cat D.Va",
    imageUrl: "",
    skuIds: [9068],
  },
  {
    id: "mccree_hanzo_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "McHanzo",
    imageUrl: "",
    skuIds: [9069],
  },
  {
    id: "ophiura_charm",
    type: "design",
    artist: "Yuli",
    medium: "charm",
    title: "The Boy :3c",
    imageUrl: "",
    skuIds: [9070],
  },
  {
    id: "maya_bookmark",
    type: "design",
    artist: "Yuli",
    medium: "bookmark",
    title: "Burgers/Ramen!",
    imageUrl: "",
    productOptions: {
      side: ["Double-sided"],
    },
    skuIds: [9071],
  },
  {
    id: "narumitsu_bookmark",
    type: "design",
    artist: "Yuli",
    medium: "bookmark",
    title: "Chained By Fate",
    imageUrl: "",
    productOptions: {
      side: ["Double-sided"],
    },
    skuIds: [9072],
  },
  {
    id: "rivals_ash_gary_pikachu_eevee_bookmark",
    type: "design",
    artist: "Yuli",
    medium: "bookmark",
    title: "Partner Pokemon",
    imageUrl: "",
    productOptions: {
      side: ["Double-sided"],
    },
    skuIds: [9073],
  },
  {
    id: "team_rocket_jessie_james_meowth_bookmark",
    type: "design",
    artist: "Yuli",
    medium: "bookmark",
    title: "Photo Op",
    imageUrl: "",
    productOptions: {
      side: ["Double-sided"],
    },
    skuIds: [9074],
  },
  // begin buttons
  {
    id: "one_punch_man_saitama_serious",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Saitama (srs)",
    imageUrl: "",
    skuIds: [9075],
  },
  {
    id: "one_punch_man_saitama_silly",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Saitama (silly)",
    imageUrl: "",
    skuIds: [9076],
  },
  {
    id: "one_punch_man_genos_serious",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Genos (srs)",
    imageUrl: "",
    skuIds: [9077],
  },
  {
    id: "one_punch_man_genos_silly",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Genos (silly)",
    imageUrl: "",
    skuIds: [9078],
  },
  {
    id: "one_punch_man_sonic_serious",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Sonic (srs)",
    imageUrl: "",
    skuIds: [9079],
  },
  {
    id: "one_punch_man_sonic_silly",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Sonic (silly)",
    imageUrl: "",
    skuIds: [9080],
  },
  {
    id: "one_punch_man_tornado_serious",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Tornado (srs)",
    imageUrl: "",
    skuIds: [9081],
  },
  {
    id: "one_punch_man_tornado_silly",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "OPM - Tornado (silly)",
    imageUrl: "",
    skuIds: [9082],
  },
  {
    id: "love_live_honoka",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Honoka",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9083],
  },
  {
    id: "love_live_nico",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live -  Nico",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9084],
  },
  {
    id: "love_live_eli",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Eli",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9085],
  },
  {
    id: "love_live_rin",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Rin",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9086],
  },
  {
    id: "love_live_hanayo",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Hanayo",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9087],
  },
  {
    id: "love_live_umi",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Umi",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9088],
  },
  {
    id: "love_live_nozomi",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Nozomi",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9089],
  },
  {
    id: "love_live_kotori",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Kotori",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9090],
  },
  {
    id: "love_live_maki",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Love Live - Maki",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9091],
  },
  {
    id: "pokemon_charmander",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Pokemon - Charmander",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9092],
  },
  {
    id: "pokemon_bulbasaur",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Pokemon - bulbasaur",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9093],
  },
  {
    id: "pokemon_squirtle",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Pokemon - squirtle",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9094],
  },
  {
    id: "pokemon_pikachu",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Pokemon - pikachu",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9095],
  },
  {
    id: "pokemon_raichu",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Pokemon - raichu",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9096],
  },
  {
    id: "persona_teddie",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Persona - Teddie",
    imageUrl: "",
    skuIds: [9097],
  },
  {
    id: "metroid_samus",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Metroid - Samus",
    imageUrl: "",
    skuIds: [9098],
  },
  {
    id: "ace_attorney_phoenix_button",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Ace Attorney - Phoenix",
    imageUrl: "",
    skuIds: [9099],
  },
  {
    id: "ace_attorney_edgeworth_button",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Ace Attorney - Edgeworth",
    imageUrl: "",
    skuIds: [9100],
  },
  {
    id: "marths_marth",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - Marth",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9101],
  },
  {
    id: "marths_ike",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - Ike",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9102],
  },
  {
    id: "marths_chrom",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - chrom",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9103],
  },
  {
    id: "marths_lucina",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - lucina",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9104],
  },
  {
    id: "marths_morgan",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - morgan",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9105],
  },
  {
    id: "marths_hector",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - hector",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9106],
  },
  {
    id: "marths_lilina",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - lilina",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9107],
  },
  {
    id: "marths_roy",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - roy",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9108],
  },
  {
    id: "marths_morth",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "Marths - morth",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9109],
  },
  {
    id: "su_garnet",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - Garnet",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9110],
  },
  {
    id: "su_amethyst",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - amethyst",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9111],
  },
  {
    id: "su_pearl",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - pearl",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9112],
  },
  {
    id: "su_steven",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - steven",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9113],
  },
  {
    id: "su_connie",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - connie",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9114],
  },
  {
    id: "su_lion",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - lion",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9115],
  },
  {
    id: "su_young_greg",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - young_greg",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9116],
  },
  {
    id: "su_old_greg",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - old_greg",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9117],
  },
  {
    id: "su_rose",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - rose",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9118],
  },
  {
    id: "su_ruby",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - ruby",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9119],
  },
  {
    id: "su_sapphire",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - sapphire",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9120],
  },
  {
    id: "su_lapis",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - lapis",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9121],
  },
  {
    id: "su_peridot",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - peridot",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9122],
  },
  {
    id: "su_stevonnie",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - stevonnie",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9123],
  },
  {
    id: "su_its_okay",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - its_okay",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9124],
  },
  {
    id: "su_its_over",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - its_over",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9125],
  },
  {
    id: "su_bismuth",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - bismuth",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9126],
  },
  {
    id: "su_jasper",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - jasper",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9127],
  },
  {
    id: "su_cookie_cat",
    type: "design",
    artist: "Yuli",
    medium: "button",
    title: "SU - cookie_cat",
    imageUrl: "",
    hideFromList: true,
    skuIds: [9128],
  },
  {
    id: "planner_overwatch",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    title: "Overwatch Planner Stickers",
    imageUrl: "",
    productOptions: {
      size: ["Sheet"],
      quality: ["Good"],
    },
    skuIds: [9129],
  },
  {
    id: "planner_pikachu",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    title: "Pikachu Planner Stickers",
    imageUrl: "",
    productOptions: {
      size: ["Sheet"],
      quality: ["Good"],
    },
    skuIds: [9130],
  },
  {
    id: "pokemon_gen_1",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    title: "Gen 1 Stickers",
    imageUrl: "",
    productOptions: {
      size: ["Sheet"],
      quality: ["Good"],
    },
    skuIds: [9131],
  },
  {
    id: "pokemon_gen_2",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    title: "Gen 2 Stickers",
    imageUrl: "",
    productOptions: {
      size: ["Sheet"],
      quality: ["Good"],
    },
    skuIds: [9132],
  },
  {
    id: "badges_gen_1",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    title: "Gen 1 Badges",
    imageUrl: "",
    productOptions: {
      size: ["Small"],
      quality: ["Good"],
    },
    skuIds: [9133],
  },
  {
    id: "badges_gen_1",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    title: "Gen 2 Badges",
    imageUrl: "",
    productOptions: {
      size: ["Small"],
      quality: ["Good"],
    },
    skuIds: [9134],
  },
  {
    id: "single_sticker",
    type: "design",
    artist: "Yuli",
    medium: "stickers",
    imageUrl: "",
    productOptions: {
      size: ["Tiny"],
      quality: ["Good"],
    },
    skuIds: [9135],
  },
  // {
  //   id: "one_punch_man_saitama_serious",
  //   type: "design",
  //   artist: "Yuli",
  //   medium: "button",
  //   title: "OPM - Saitama (srs)",
  //   imageUrl: "",
  //   hideFromList: true,
  //   skuIds: [91],
  // },
  // {
  //   id: "",
  //   type: "design",
  //   artist: "Yuli",
  //   medium: "print",
  //   title: "",
  //   imageUrl: "",
  //   productOptions: {
  //       size: ["Mini", "Small", "Medium", "Large"],
  //       finish: ["Matte", "Holographic"]
  //   },
  //   skuIds: [91]
  // },
];

const skus = [
  {
    id: 1,
    parentId: "kirby_adventure_vv",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
];

const sets = [
  {
    id: "kirby_postcards",
    title: "Kirby's Adventure Postcard Set",
    type: "set",
    artist: "Jupebox",
    skuIds: [1, 2, 3, 4, 5, 6, 7, 8],
    price: 30,
    discount: 10,
  },
];

const discountRules = [
  {
    id: 1,
    title: "3 Mini Prints for $5",
    medium: "print",
    quantity: 3,
    size: "Mini",
    discount: 1,
  },
];
const skus = [
  {
    id: 9001,
    parentId: "guide_to_marths",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9002,
    parentId: "wonder_woman",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9003,
    parentId: "wonder_woman",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9004,
    parentId: "wonder_woman",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9005,
    parentId: "rick_and_morty",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9006,
    parentId: "rick_and_morty",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9007,
    parentId: "love_live_ice_cream",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9008,
    parentId: "love_live_ice_cream",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9009,
    parentId: "love_live_ice_cream",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9010,
    parentId: "illumi_natu",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9011,
    parentId: "illumi_natu",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9012,
    parentId: "illumi_natu",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9013,
    parentId: "illumi_natu",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9014,
    parentId: "hisoka",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9015,
    parentId: "hisoka",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9016,
    parentId: "hisoka",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9017,
    parentId: "together_breakfast",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9018,
    parentId: "together_breakfast",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9019,
    parentId: "together_breakfast",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Thin",
    },
    inventory: 10,
  },
  {
    id: 9020,
    parentId: "together_breakfast",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9021,
    parentId: "together_breakfast",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9022,
    parentId: "live_laugh_love_chara_undertale",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9023,
    parentId: "live_laugh_love_chara_undertale",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9024,
    parentId: "live_laugh_love_chara_undertale",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9025,
    parentId: "live_laugh_love_chara_undertale",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9026,
    parentId: "junkrat_bakugou_my_hero_academia_overwatch",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9027,
    parentId: "junkrat_bakugou_my_hero_academia_overwatch",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9028,
    parentId: "samus_zero_suit",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9029,
    parentId: "samus_zero_suit",
    type: "sku",
    options: {
      size: "Small",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9030,
    parentId: "samus_zero_suit",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9031,
    parentId: "narumitsu_ace_attorney_edgeworth_phoenix",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9032,
    parentId: "narumitsu_ace_attorney_edgeworth_phoenix",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9033,
    parentId: "narumitsu_ace_attorney_edgeworth_phoenix",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Thin",
    },
    inventory: 10,
  },
  {
    id: 9034,
    parentId: "narumitsu_ace_attorney_edgeworth_phoenix",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9035,
    parentId: "narumitsu_ace_attorney_edgeworth_phoenix",
    type: "sku",
    options: {
      size: "Large",
      finish: "Thin",
    },
    inventory: 10,
  },
  {
    id: 9036,
    parentId: "wind_waker_house_soup",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9037,
    parentId: "wind_waker_house_soup",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9038,
    parentId: "bubble_bobble",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9039,
    parentId: "bubble_bobble",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9040,
    parentId: "sakura_regret_space",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9041,
    parentId: "sakura_regret_space",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9042,
    parentId: "sakura_regret_space",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9043,
    parentId: "sherlock_redbeard_kids",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9044,
    parentId: "sherlock_redbeard_kids",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9045,
    parentId: "sherlock_redbeard_kids",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9046,
    parentId: "sherlock_wedding_planning",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9047,
    parentId: "sherlock_wedding_planning",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9048,
    parentId: "high_tea_overwatch_mccree_hanzo_nani_the_fuck",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9049,
    parentId: "moira_guess_youll_die_overwatch",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9050,
    parentId: "pikachus_apples_trees",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9051,
    parentId: "pikachus_apples_trees",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9052,
    parentId: "morth_portrait",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9053,
    parentId: "corgi_beer_watson",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9054,
    parentId: "mob_psycho_salt",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9055,
    parentId: "mob_psycho_salt",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9056,
    parentId: "my_hero_academia_arcade",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9057,
    parentId: "my_hero_academia_arcade",
    type: "sku",
    options: {
      size: "Large",
      finish: "Holographic",
    },
    inventory: 10,
  },
  {
    id: 9058,
    parentId: "shera_dnd",
    type: "sku",
    options: {
      size: "Medium",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9059,
    parentId: "shera_dnd",
    type: "sku",
    options: {
      size: "Large",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9058,
    parentId: "full_moon_wo_sagashite",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9059,
    parentId: "full_moon_wo_sagashite",
    type: "sku",
    options: {
      size: "Small",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9060,
    parentId: "full_moon_wo_sagashite",
    type: "sku",
    options: {
      size: "Matte",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9061,
    parentId: "sonic_shitpost_gun",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9062,
    parentId: "sonic_shitpost_nya",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9063,
    parentId: "sonic_shitpost_nya",
    type: "sku",
    options: {
      size: "Mini",
      finish: "Matte",
    },
    inventory: 10,
  },
  {
    id: 9064,
    parentId: "narumitsu_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9065,
    parentId: "maya_pearl_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9066,
    parentId: "moira_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9067,
    parentId: "mei_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9068,
    parentId: "dva_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9069,
    parentId: "mccree_hanzo_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9070,
    parentId: "ophiura_charm",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9071,
    parentId: "maya_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 10,
  },
  {
    id: 9072,
    parentId: "narumitsu_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 10,
  },
  {
    id: 9073,
    parentId: "rivals_ash_gary_pikachu_eevee_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 10,
  },
  {
    id: 9074,
    parentId: "team_rocket_jessie_james_meowth_bookmark",
    type: "sku",
    options: {
      side: "Double-sided",
    },
    inventory: 10,
  },
  {
    id: 9075,
    parentId: "one_punch_man_saitama_serious",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9076,
    parentId: "one_punch_man_saitama_silly",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9077,
    parentId: "one_punch_man_genos_serious",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9078,
    parentId: "one_punch_man_genos_silly",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9079,
    parentId: "one_punch_man_sonic_serious",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9080,
    parentId: "one_punch_man_sonic_silly",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9081,
    parentId: "one_punch_man_tornado_serious",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9082,
    parentId: "one_punch_man_tornado_silly",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9083,
    parentId: "love_live_honoka",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9084,
    parentId: "love_live_nico",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9085,
    parentId: "love_live_eli",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9086,
    parentId: "love_live_rin",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9087,
    parentId: "love_live_hanayo",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9088,
    parentId: "love_live_umi",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9089,
    parentId: "love_live_nozomi",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9090,
    parentId: "love_live_kotori",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9091,
    parentId: "love_live_maki",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9092,
    parentId: "pokemon_charmander",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9093,
    parentId: "pokemon_bulbasaur",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9094,
    parentId: "pokemon_squirtle",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9095,
    parentId: "pokemon_pikachu",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9096,
    parentId: "pokemon_raichu",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9097,
    parentId: "persona_teddie",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9098,
    parentId: "metroid_samus",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9099,
    parentId: "ace_attorney_phoenix_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9100,
    parentId: "ace_attorney_edgeworth_button",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9101,
    parentId: "marths_marth",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9102,
    parentId: "marths_ike",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9103,
    parentId: "marths_chrom",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9104,
    parentId: "marths_lucina",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9105,
    parentId: "marths_morgan",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9106,
    parentId: "marths_hector",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9107,
    parentId: "marths_lilina",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9108,
    parentId: "marths_roy",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9109,
    parentId: "marths_morth",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9110,
    parentId: "su_garnet",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9111,
    parentId: "su_amethyst",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9112,
    parentId: "su_pearl",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9113,
    parentId: "su_steven",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9114,
    parentId: "su_connie",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9115,
    parentId: "su_lion",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9116,
    parentId: "su_young_greg",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9117,
    parentId: "su_old_greg",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9118,
    parentId: "su_rose",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9119,
    parentId: "su_ruby",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9120,
    parentId: "su_sapphire",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9121,
    parentId: "su_lapis",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9122,
    parentId: "su_peridot",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9123,
    parentId: "su_stevonnie",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9124,
    parentId: "su_its_okay",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9125,
    parentId: "su_its_over",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9126,
    parentId: "su_bismuth",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9125,
    parentId: "su_jasper",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9128,
    parentId: "su_cookie_cat",
    type: "sku",
    inventory: 10,
  },
  {
    id: 9129,
    parentId: "planner_overwatch",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 9130,
    parentId: "planner_pikachu",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 9131,
    parentId: "pokemon_gen_1",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 9132,
    parentId: "pokemon_gen_2",
    type: "sku",
    options: {
      size: "Sheet",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 9133,
    parentId: "pokemon_gen_1",
    type: "sku",
    options: {
      size: "Small",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 9134,
    parentId: "pokemon_gen_1",
    type: "sku",
    options: {
      size: "Small",
      quality: "Good",
    },
    inventory: 21,
  },
  {
    id: 9135,
    parentId: "single_sticker_yuli",
    type: "sku",
    options: {
      size: "Tiny",
      quality: "Good",
    },
    inventory: 21,
  },
];
